### ISSUE TITLE
[alpha testing] behavioral issue

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team15#110]
로그인 후 `back` 버튼을 누르면 로그아웃됩니다.

**Comment by lightb0x** [comment]
또한 이 다음 다시 로그인하면 `Profile`, `settings` 등이 작동하지 않습니다.

**Comment by taehwoi** [comment]
Profile Settings가 작동이 안되는 것은 아마 버튼 인식공간이 조금 작아서 그런 것 같은데 다시 한 번 확인해보겠습니다 감사합니다!

**Comment by taehwoi** [comment]
로그인 후 뒤로가기 시 로그인 페이지가 뜨는 건 구글, 네이버, 쿠팡 또한 그렇고 다시 앞으로 가면 로그인 세션이 유지되는 것으로 알고 있습니다. 아예 로그아웃이 되었었나요?
피드백 감사드립니다.

**Comment by lightb0x** [comment]
로그인 페이지가 표시되어서 로그아웃되는지 알았는데,
로그아웃되지는 않고 프로필 등이 접근 가능한 것으로 보아 로그아웃되지는 않는 것 같습니다.

뒤로가기 버튼을 눌렀을 때 로그인 페이지가 표시되면 로그아웃된 것으로 알 수 있으니 로그인 페이지로는 뒤로가기되지 않으면 좋을것같습니다.

**Comment by lightb0x** [comment]
또한 두번째로 달았던,
> 이 다음 다시 로그인하면 `Profile`, `settings` 등이 작동하지 않습니다.

는 #111 과 같은 문제로, 첫번째 달았던 것과는 무관한것같습니다.
