### ISSUE TITLE
Fix onClick function for Q&A cards

### ISSUE THREAD

**Issue by rachelg98** [swsnu/swpp2019-team15#127]
Currently the Question and Answer view cards automatically redirect to Question detail page on click. It's prone to users being unintentionally redirected when trying to highlight text or accidental clicking which can be a bit annoying. 

Perhaps we can restrain the onClick function to only the Question text instead and allow the user to view a person's profile by clicking on the username. What do you guys think?

**Comment by taehwoi** [comment]
I think that is a good idea
