### ISSUE TITLE
Sending push notifications to users in frontend

### ISSUE THREAD

**Issue by rachelg98** [swsnu/swpp2019-team15#26]
When a Question is posted by a user to to the backend or an Answer to a Question has been posted, we need to implement a feature that can send web push notifications to clients in the target location. What are your thoughts on using  websockets with Redis or Firebase Cloud Messaging to implement this feature? 

Firebase 
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

Redis
https://github.com/jrief/django-websocket-redis

**Comment by taehioum** [comment]
I have question. Does django-webpush library require django to be used in the frontend as well?

**Comment by taehioum** [comment]
My idea of a push notification was something along the lines of
Django to React via websocket
React to Browser via service worker
All the popular frameworks seemed to work under the assumption that django is used in the frontend... but if it works, I have no issue.

**Comment by rachelg98** [comment]
The django-webpush library also seems to work under the assumption that django is used as the frontend, but I'm not sure if configuring serviceWorker in React frontend to send requests to dango backend would work well too. 
Alternatively, using Django Channels with websockets for bidirectional communication seems to be a popular option.

**Comment by taehioum** [comment]
I think using django channels is a good idea. That way we can isolate push notification(to the browser) feature and first focus on establishing a web socket communication between two ends

**Comment by taehioum** [comment]
By the way, can you restore the requirements.txt file in feature/notification? 
It is used by travis to install needed python packages easily.

**Comment by taehioum** [comment]
I think using push might be a better idea than a websocket as it is alive even if our app is closed.

The server can talk to our app via websocket, and we can respond with traditional http?

**Comment by rachelg98** [comment]
Sure. I'll restore the requirements.txt file. I think i might have removed it unknowingly in the recent commit.
