### ISSUE TITLE
Travis disabled?

### ISSUE THREAD

**Issue by taehioum** [swsnu/swpp2019-team15#27]
Didn't we have travis in our install apps???

**Comment by Minji1234** [comment]
You mean on master branch? We have travis on our master branch and checked it was working on last thursday.

**Comment by taehioum** [comment]
No I think all our branches are fine but in here:
[https://github.com/swsnu/swpp2019-team15/settings/installations
](url)

It seems like all our new pull requests are not sent to travis

**Comment by taehioum** [comment]
Dunno what happened, but its working again
