### ISSUE TITLE
Adding new view which can check past questions and answers history

### ISSUE THREAD

**Issue by Minji1234** [swsnu/swpp2019-team15#3]
At main page if we click question in 'My Questions', the user can check that question.
So how about adding 'Past Questions' button in main page which renders past questions list.
If user clicks one of past question button then it renders like Detail Page.
I want to hear your opinions.

**Comment by taehioum** [comment]
I agree that we need past questions, but not sure whether they should be accessible from the profile page, or the main page.

**Comment by rachelg98** [comment]
That sounds like a good idea. I think the design would look more intuitive and perhaps a bit cleaner if we implement 'Past Questions' in the main page using a toggle button to filter the question list, or split them into tabs. It would also reduce the number of clicks the user has to make to access their own question list.
