### ISSUE TITLE
Notifying users upon question creation and answer creation

### ISSUE THREAD

**Issue by taehioum** [swsnu/swpp2019-team15#42]
In branch features/notify_users,
I have implemented a skeleton code that sends notification to every user that have subscribed upon question creation. ( The subscription check is done by send_push)
Can you please improve this method (better name? check if user is near the question's target location, ....)
and also implement method to be called upon answer creation? I believe the user pool to be notified upon answer creation is simple, lets just send to the owner of the question. (We might extend it by letting other users subscribe to a question they will be interested in.... but that's sometime later)

**Comment by taehioum** [comment]
To access all the features in the branch,

please run
```pip install -r requirements.txt``` (virtual env recommended) in backend/

**Comment by Minji1234** [comment]
Okay. I will make it

**Comment by Minji1234** [comment]
python manage.py process_tasks
