### ISSUE TITLE
Missing subscribe button

### ISSUE THREAD

**Issue by Minji1234** [swsnu/swpp2019-team15#59]
I found there is no subscribe button in question page, though I remember when it existed.
I wonder if it has some problem so it was deleted from dev branch or not.
Was it deleted by fault or on purpose?

**Comment by taehwoi** [comment]
The subscribe button was there for testing purposes, so I didn't push it to dev branch.
I think the subscritbe button should go the the settings page hen the settings page is ready.
@rachelg98

**Comment by Minji1234** [comment]
I got it. Thanks for information
