### ISSUE TITLE
Adding map on Answer page

### ISSUE THREAD

**Issue by Minji1234** [swsnu/swpp2019-team15#60]
It will be much better if there is marker on location which shows question_location.
I tried reusing our GoogleMap by transferring location information from NewAnswer.js, but it was not that easy.
I will try it again tomorrow if nobody has interest on it.

**Comment by taehwoi** [comment]
If there was any error when importing the map component to the answer page, it is because my google API only allows the map to open in certain sites (e.g. localhost/question/create, locahost/map/ ...)
I have added localhost/reply/* to my API, so it should work. If it doesn't, please tell me.

**Comment by taehwoi** [comment]
And I think the priority should be high, this sounds like a nice feature.
Current Map only accepts markers when coordinates are given by the searchbox; I will see if I can fix it so that it can accept coordinates to display the marker.

**Comment by Minji1234** [comment]
If coordinates can be handed over from forms like '< Map latitude={selectedquestion.latitude}, longitude={selectedquestion.longitude}, isMapForAnswer=true / >', and then it will be much easier to use in Answer page.
