### ISSUE TITLE
Let's change stored time to KST

### ISSUE THREAD

**Issue by Minji1234** [swsnu/swpp2019-team15#68]
Our stored time is not KST, so there is a need to change it to KST.

**Comment by taehwoi** [comment]
Now that you mention time, I think it would be nice to show time in 1, 3, 5, 10 minutes ago.

**Comment by rachelg98** [comment]
I created a branch feat/change_timezone to fix the timezone issue. The timezone in backend settings was already 'Asia/Seoul' from the start but it seems that in order for the django's date_time field to use the custom timezone the solution is to change USE_TZ to false. 
Additionally it would also be nice to clean up the time string to make it more readable

**Comment by Minji1234** [comment]
@rachelg98 Thanks. And I also agree with your idea.
