### ISSUE TITLE
Things to be implemented from peer feedback.

### ISSUE THREAD

**Issue by taehwoi** [swsnu/swpp2019-team15#87]
An incentive for an user to answer a question. (Karma system, points, achievements...)

A way to detect malicious users. (how off is the user's answer from the average?)

What to do when there are no replies from users?

ML.

**Comment by Minji1234** [comment]
There is a minor issue to be fixed in reply detail page. When the user clicks link on the push, it redirects to reply detail page but it shows time in invalid format.
